image:
  repository: bitnamilegacy/mongodb # TODO: related to change in bitnami to remove the original dockerhub repos under bitnami, consider to change to image maintaned

resources:
  requests:
    memory: ${resources_requests_memory}
    cpu: ${resources_requests_cpu}
  limits:
    memory: ${resources_limits_memory}
    cpu: ${resources_limits_cpu}
