# NOTE: we set/switch image repository related to change in bitnami to remove the original bitnami org/repository dockerhub repos and migrate all existing/old images to bitnamilegacy, for more info check https://github.com/bitnami/containers/issues/83267
# TODO: consider a change to use another image repository which is maintained
image:
  repository: bitnamilegacy/mongodb

resources:
  requests:
    memory: ${resources_requests_memory}
    cpu: ${resources_requests_cpu}
  limits:
    memory: ${resources_limits_memory}
    cpu: ${resources_limits_cpu}
