name: Checkov
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      discussions: write
      pull-requests: write
      security-events: write
      id-token: write
    strategy:
      matrix:
        path:
          - modules/defectdojo
          - modules/authentik
          - modules/cnpg
          - modules/external-secret
          - modules/event-exporter
          - modules/gateway-api-crds
          - modules/github-actions-runner
          - modules/gitlab-runner
          - modules/goldilocks
          - modules/horizon-monitor
          - modules/istio
          - modules/k8s/namespace
          - modules/kafka
          - modules/keycloak
          - modules/keeper-reader
          - modules/kyverno
          - modules/loki
          - modules/minio
          - modules/mongodb
          - modules/mongodb-bi-connector
          - modules/onepassword
          - modules/onepassword_to_secret_manager
          - modules/qdrant
          - modules/renovate-bot
          - modules/sentry
          - modules/service
          - modules/supabase

    steps:
    - uses: dasmeta/reusable-actions-workflows/checkov@main
      with:
        fetch-depth: 0
        directory: ${{ matrix.path }}
      continue-on-error: true
