name: Terraform Test
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  terraform-validate:
    permissions:
      actions: write
      contents: write
      discussions: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - modules/defectdojo
          - modules/authentik
          - modules/cnpg
          - modules/external-secret
          - modules/event-exporter
          - modules/gateway-api-crds
          - modules/gitlab-runner
          - modules/horizon-monitor
          - modules/istio
          - modules/k8s/namespace
          - modules/keycloak
          - modules/keeper-reader
          - modules/kyverno
          - modules/loki
          - modules/mongodb-bi-connector
          - modules/onepassword
          - modules/onepassword_to_secret_manager
          - modules/qdrant
          - modules/random-secret-values
          - modules/renovate-bot
          - modules/sentry
          - modules/service
          - modules/supabase

    steps:
    - uses: dasmeta/reusable-actions-workflows/terraform-test@main
      with:
        aws-region: ${{ secrets.AWS_REGION}}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        path: ${{ matrix.path }}
      continue-on-error: true
